### ISSUE TITLE
APP TITLE AND LOGIN

### ISSUE THREAD

**Issue by brixxnatt** [marcopeocchi/yt-dlp-web-ui#89] opened 2023-09-23 14:27 UTC
hello   ,
1-APP TITLE do not change inside the pages , only at the browser header
2-Login user name and password , should always be presented per session
3- when we download via your script , the files is always 644 permission , it needs to be always 755 permission

thanks

**Comment by marcopeocchi** [comment] 2023-09-23 18:35
hi @brixxnatt,

1) ok, I'll provide a way to change that
2) being presented per session it implies that the session cookie should have a short expire time, which is non deterministic behaviour. By design the session cookie has a TTL of 30 days. One thing that's possible will be changing the TTL via the config file
3) 644 is correct, the file should not be executable and only readable from other users. Anyway, it's not my web-ui, those permission are set be yt-dlp itself IIRC

**Comment by brixxnatt** [comment] 2023-09-24 06:25
yes ttl should be configued as this is a major secutiry issue since the script can upload and delete videos , so i guess is better is to have a login session once we logout , logout and login is needed to this type of scripts please
 - as for the 664  , i made a script listen to the folder content and change any downloaded video to 755  , i thought there is a way in your script to do that .  anyway  , the ebst thing is to do a login logout username and password ,even with or without the ttl .

**Comment by brixxnatt** [comment] 2023-09-24 12:28
or its okay we can do ngx_http_auth_basic_module in nginx

**Comment by marcopeocchi** [comment] 2023-09-25 19:19
i wanted to reopen this issue to re-iterate to some points.

After enabling authentication, via config or cli params, you'll find this screen
![immagine](https://github.com/marcopeocchi/yt-dlp-web-ui/assets/35533749/325a01b8-fd6e-46a8-886e-652473de8fc5)
After filling the login form
![immagine](https://github.com/marcopeocchi/yt-dlp-web-ui/assets/35533749/0c574a01-ee87-4248-ba5c-ede9c0801233)
![immagine](https://github.com/marcopeocchi/yt-dlp-web-ui/assets/35533749/d91c9fd2-f965-4bdb-afb9-593e37a42deb)

Once logged in the clicking the icon-button for the log-ing page logs you out.
Once logged-off the session cookie will be invalidated and removed.

If you're logged out, instead, it provides you the ability to log-in again.

**Comment by brixxnatt** [comment] 2023-10-06 21:16
i thank you the 755 files fixed , i have no idea where to put this or how to work it

Usage yt-dlp-webui:
  -auth
        Enable RPC authentication
  -conf string
        Config file path
  -driver string
        yt-dlp executable path (default "yt-dlp")
  -out string
        Where files will be saved (default ".")
  -port int
        Port where server will listen at (default 3033)
  -qs int
        Download queue size (default 8)
  -user string
        Username required for auth
  -pass string
        Password required for auth

**Comment by marcopeocchi** [comment] 2023-10-07 13:27
@brixxnatt i'm glad that the "files permission" thing has found a fix. Can you please explain more the second part? :raised_eyebrow:

**Closed** 2023-10-22 09:56 UTC
